### ISSUE TITLE
Завести автодеплой на Тревисе

### ISSUE THREAD

**Issue by pepelsbey** [pitercss/pitercss.ru#2]
…чтобы можно было добавить презентацию просто закоммитив её сюда, а она сразу же на сервере. Как и что — можно спросить у Миши Баранова @h4, он собаку съел на этом :)

**Comment by Gurylev** [comment]
А его не проще опубликовать сразу из мастера? https://pitercss.github.io/pitercss.ru/
Никаких автодеплоев настраивать не потребуется. Вроде в проекте только статика. Сборка ей не нужна.

**Comment by h4** [comment]
Инфраструктура гитхаба подвержена внезапным падениям, это главный аргумент
в пользу деплоя на свой сервер. А ещё это просто интереснее.

**Comment by Gurylev** [comment]
@h4 только мне кажется, что для сайта с презентациями это не так принципиально? Если сайт конференции - да. Если сайт митапа - нууу, хз. Но сайт с презентациями - хз вообще, зачем доставку усложнять.

**Comment by pepelsbey** [comment]
Я регулярно вижу, когда IP Гитхаба заблокированы и не открываются то у тех, то у других провадеров. К тому же хочется, чтобы это был не сайт с презентациями, а сайт сообщества. С архивом, страницами, фото, видео. У нас куча материалов скопилось, было бы хорошо его показать :)

**Comment by Gurylev** [comment]
А вот блокировка провайдеров - это достойная причина. Про это-то я и забыл.
Про сайт понял. Но это уже для другой ишьи #5.

**Comment by h4** [comment]
@pepelsbey я так понимаю, что pitercss.ru крутится на каком-то отдельном серваке?

**Comment by pepelsbey** [comment]
Да, это сервер на DO.

**Comment by h4** [comment]
Мне нужен ssh доступ туда с правами вызова sudo. 

Если что, вот ключ:
```sh
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQmtYchmDwFvwE0qj1sRW6e7tCfn3oz+e8k64lE/2N6W1rV5vZsEIBomCERChtDG77USKaCv3c7lQijJKLQiCCi178+m52ZiHlYaPwyQ81xbRanvXB3goWF15JvquacPnuVoo0EU6OqCDRSMMheukgxG+glR84qRybgGgF01MCu1WHwXLjNxztTponOkrpRnY1toxM3LVo7B3zgzxbIq049gdpWVcci+eua/mx3zfW6r4hDTCxcPB5EzwPQJtP+dm4OdbYNBD2GpVxRwkIjkc1IWsRy2Z0e8EbLlmz5XEj0nBtOFzZWkRvqIJTyKZF0qgozvvGUVgIIjxK39H3MBIL
```
